language: c
sudo: false
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.6

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install: raco pkg install --deps search-auto cover-coveralls $TRAVIS_BUILD_DIR

script:
  - raco make $TRAVIS_BUILD_DIR/yaml/main.rkt
  - raco test $TRAVIS_BUILD_DIR/yaml

after_success:
  - cd $TRAVIS_BUILD_DIR/yaml
  - raco cover -f coveralls .
